version: '3.7'

services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb-${ID}
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PW}
      - MYSQL_DATABASE=${MARIADB_SCHEMA}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PW}
    volumes:
      - ${MARIADB_VOLUME}:/var/lib/mysql
    ports:
      - '${MARIADB_EXT_PORT}:3306'
    networks:
      - devh-network
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: elasticsearch-${ID}
    environment:
      - discovery.type=single-node
      - cluster.name=${ID}-cluster
      - node.name=${ID}-node
      - reindex.remote.whitelist=0.0.0.0:9200
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_MEMORY_MB}m -Xmx${ES_MEMORY_MB}m"
    volumes:
      - ${ES_VOLUME}:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '${ES_EXT_PORT}:9200'
    networks:
      - devh-network
      
networks:
  devh-network:
    external: true

